/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bootstrap */
        get: operations["bootstrap_api_v1_bootstrap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Context Targets */
        get: operations["get_context_targets_api_v1_context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/context/{target}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Context Target */
        get: operations["get_context_target_api_v1_context__target__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/context/{target}/prepare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Prepare Context */
        post: operations["prepare_context_api_v1_context__target__prepare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/context/{target}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Context */
        post: operations["confirm_context_api_v1_context__target__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Item */
        get: operations["get_item_api_v1_items__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/items/{id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Catalog Item Content */
        put: operations["update_catalog_item_content_api_v1_catalog_items__id__content_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/items/rename": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rename Catalog Skill */
        post: operations["rename_catalog_skill_api_v1_catalog_items_rename_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/items/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete Catalog Skill */
        post: operations["delete_catalog_skill_api_v1_catalog_items_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apps/{app_id}/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get App Health */
        get: operations["get_app_health_api_v1_apps__app_id__health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apps/{app_id}/launch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Launch App */
        post: operations["launch_app_api_v1_apps__app_id__launch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rebuild Source Index */
        post: operations["rebuild_source_index_api_v1_sources_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usage/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Usage Summary */
        get: operations["get_usage_summary_api_v1_usage_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Model Snapshot */
        get: operations["get_model_snapshot_api_v1_models_snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Models */
        post: operations["refresh_models_api_v1_models_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppHealthResponse */
        AppHealthResponse: {
            /** Id */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "stopped" | "unavailable";
            /** Url */
            url?: string | null;
        };
        /** AppLaunchResponse */
        AppLaunchResponse: {
            /** Id */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "starting";
            /** Url */
            url: string;
        };
        /** AppSummary */
        AppSummary: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Category */
            category: string;
            /** Description */
            description: string;
            /** Available */
            available: boolean;
            /**
             * Launchconfigured
             * @default false
             */
            launchConfigured: boolean;
            /** Url */
            url: string;
            /** Pathhint */
            pathHint: string;
            /** Stack */
            stack: string;
            /** Status */
            status: string;
            /**
             * Createdat
             * Format: date
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date
             */
            updatedAt: string;
            /** Screenshot */
            screenshot: string;
            /** Screenshotlabel */
            screenshotLabel: string;
            /** Reason */
            reason?: string | null;
        };
        /** Authority */
        Authority: {
            /**
             * Ssot
             * @default filesystem
             * @constant
             */
            ssot: "filesystem";
            /**
             * Cache
             * @default sqlite
             * @constant
             */
            cache: "sqlite";
            /**
             * Cachereconstructible
             * @default true
             * @constant
             */
            cacheReconstructible: true;
        };
        /** BootstrapResponse */
        BootstrapResponse: {
            /**
             * Apiversion
             * @default v1
             * @constant
             */
            apiVersion: "v1";
            /**
             * Profile
             * @default local-api
             * @constant
             */
            profile: "local-api";
            /**
             * Generatedat
             * Format: date-time
             */
            generatedAt?: string;
            /**
             * Fallbackmode
             * @default none
             * @constant
             */
            fallbackMode: "none";
            authority?: components["schemas"]["Authority"];
            capabilities: components["schemas"]["Capabilities"];
            /** Sources */
            sources: components["schemas"]["SourceSummary"][];
            /** Apps */
            apps: components["schemas"]["AppSummary"][];
            /** Items */
            items: components["schemas"]["CatalogItem"][];
        };
        /** Capabilities */
        Capabilities: {
            catalogRead: components["schemas"]["Capability"];
            catalogManage: components["schemas"]["Capability"];
            catalogContentWrite: components["schemas"]["Capability"];
            sourceScan: components["schemas"]["Capability"];
            usageInsights: components["schemas"]["Capability"];
            contextMonitor: components["schemas"]["Capability"];
            contextOptimization: components["schemas"]["Capability"];
            appLaunching: components["schemas"]["Capability"];
            modelRefresh: components["schemas"]["Capability"];
        };
        /** Capability */
        Capability: {
            /** Available */
            available: boolean;
            /** Reason */
            reason?: string | null;
        };
        /** CatalogContentUpdateRequest */
        CatalogContentUpdateRequest: {
            /** Content */
            content: string;
            /** Expectedrevision */
            expectedRevision: string;
        };
        /** CatalogContentUpdateResponse */
        CatalogContentUpdateResponse: {
            item: components["schemas"]["CatalogItem"];
            /**
             * Backupcreated
             * @default true
             * @constant
             */
            backupCreated: true;
        };
        /** CatalogDeleteRequest */
        CatalogDeleteRequest: {
            /** Itemid */
            itemId: string;
            /** Confirm */
            confirm: string;
        };
        /** CatalogDeleteResponse */
        CatalogDeleteResponse: {
            /**
             * Status
             * @default archived
             * @constant
             */
            status: "archived";
        };
        /** CatalogIllustration */
        CatalogIllustration: {
            /** Src */
            src: string;
            /** Alt */
            alt: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "official-logo" | "official-icon" | "site-preview" | "neutral";
        };
        /** CatalogItem */
        CatalogItem: {
            /** Id */
            id: string;
            /** Key */
            key: string;
            /** Sourceid */
            sourceId: string;
            /**
             * Type
             * @enum {string}
             */
            type: "skill" | "workflow" | "prompt" | "mcp-server" | "app" | "rule";
            /**
             * Kind
             * @enum {string}
             */
            kind: "skill" | "workflow" | "prompt" | "mcp" | "command" | "app" | "rule";
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Category */
            category: string;
            /** Group */
            group: string;
            /** Commandcategory */
            commandCategory?: string | null;
            /** Commandplatform */
            commandPlatform?: ("Claude Code" | "Codex" | "Gemeinsam") | null;
            /** Origin */
            origin: string;
            /**
             * Source
             * @default local-api
             * @constant
             */
            source: "local-api";
            /** Tags */
            tags?: string[];
            /** Content */
            content: string;
            /** Revision */
            revision: string;
            /** Invoke */
            invoke?: string | null;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /** Relativepath */
            relativePath: string;
            /**
             * Owned
             * @default false
             */
            owned: boolean;
            provenance?: components["schemas"]["CatalogProvenance"] | null;
            illustration?: components["schemas"]["CatalogIllustration"] | null;
        };
        /** CatalogProvenance */
        CatalogProvenance: {
            /**
             * Classification
             * @enum {string}
             */
            classification: "first_party" | "third_party" | "derived" | "conflict" | "unknown";
            /** Providerlabel */
            providerLabel?: string | null;
            /** Homepage */
            homepage?: string | null;
            /** Repository */
            repository?: string | null;
            /** License */
            license?: string | null;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
        };
        /** CatalogRenameRequest */
        CatalogRenameRequest: {
            /** Itemid */
            itemId: string;
            /** Newslug */
            newSlug: string;
        };
        /** CatalogRenameResponse */
        CatalogRenameResponse: {
            /** Itemid */
            itemId: string;
            /**
             * Status
             * @default renamed
             * @constant
             */
            status: "renamed";
        };
        /** ContextConfirmRequest */
        ContextConfirmRequest: {
            /** Feedback */
            feedback?: string | null;
            /** Prepareid */
            prepareId: string;
            /** Draft */
            draft: string;
        };
        /** ContextConfirmResponse */
        ContextConfirmResponse: {
            /** Operationid */
            operationId: string;
            /**
             * Status
             * @default completed
             * @constant
             */
            status: "completed";
        };
        /** ContextPrepareRequest */
        ContextPrepareRequest: {
            /** Feedback */
            feedback?: string | null;
        };
        /** ContextPrepareResponse */
        ContextPrepareResponse: {
            /** Prepareid */
            prepareId: string;
            /**
             * Target
             * @enum {string}
             */
            target: "claude" | "memory" | "codex";
            /** Before */
            before: string;
            /** Preview */
            preview: string;
            /** Backupid */
            backupId: string;
            /**
             * Expiresat
             * Format: date-time
             */
            expiresAt: string;
        };
        /** ContextTargetResponse */
        ContextTargetResponse: {
            /**
             * Target
             * @enum {string}
             */
            target: "claude" | "memory" | "codex";
            /** Label */
            label: string;
            /** Sourcename */
            sourceName: string;
            /** Lines */
            lines: number;
            /** Characters */
            characters: number;
            /** Estimatedtokens */
            estimatedTokens: number;
            /**
             * Status
             * @enum {string}
             */
            status: "green" | "yellow" | "red";
            /** Content */
            content: string;
            /** Updatedat */
            updatedAt: string | null;
            /**
             * Available
             * @default true
             */
            available: boolean;
            /** Reason */
            reason?: string | null;
        };
        /** ContextTargetsResponse */
        ContextTargetsResponse: {
            /** Targets */
            targets: components["schemas"]["ContextTargetResponse"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /**
             * Adapter
             * @default local-api
             * @constant
             */
            adapter: "local-api";
            /**
             * Service
             * @default quickgraph-local-api
             * @constant
             */
            service: "quickgraph-local-api";
            /**
             * Apiversion
             * @default v1
             * @constant
             */
            apiVersion: "v1";
            /**
             * Database
             * @default ok
             * @constant
             */
            database: "ok";
        };
        /** ModelRefreshResponse */
        ModelRefreshResponse: {
            /** Updated */
            updated: number;
            /**
             * Refreshedat
             * Format: date-time
             */
            refreshedAt: string;
        };
        /** ModelSnapshotResponse */
        ModelSnapshotResponse: {
            /** Source */
            source: string;
            /**
             * Fetchedat
             * Format: date-time
             */
            fetchedAt: string;
            /** Modelcount */
            modelCount: number;
            /** Models */
            models: {
                [key: string]: unknown;
            }[];
        };
        /** ScanSourceResult */
        ScanSourceResult: {
            /** Id */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "error";
            /** Itemcount */
            itemCount: number;
            /** Fingerprint */
            fingerprint?: string | null;
            /** Reason */
            reason?: string | null;
        };
        /** ScanSourcesRequest */
        ScanSourcesRequest: {
            /**
             * Sourceids
             * @default []
             */
            sourceIds: string[];
        };
        /** ScanSourcesResponse */
        ScanSourcesResponse: {
            /** Indexed */
            indexed: number;
            /**
             * Scannedat
             * Format: date-time
             */
            scannedAt?: string;
            /** Sources */
            sources: components["schemas"]["ScanSourceResult"][];
        };
        /** SourceSummary */
        SourceSummary: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "skills" | "prompts" | "commands" | "builtins";
            /** Available */
            available: boolean;
            /** Itemcount */
            itemCount: number;
            /** Reason */
            reason?: string | null;
        };
        /** UsageDaily */
        UsageDaily: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Itemid */
            itemId: string;
            /** Count */
            count: number;
        };
        /** UsageSummaryResponse */
        UsageSummaryResponse: {
            /**
             * Adapter
             * @default local-api
             * @constant
             */
            adapter: "local-api";
            /** Daily */
            daily: components["schemas"]["UsageDaily"][];
            /**
             * Schemaversion
             * @default 1
             * @constant
             */
            schemaVersion: 1;
            summary: components["schemas"]["UsageTotals"];
            write?: components["schemas"]["UsageWriteResult"];
        };
        /** UsageTotals */
        UsageTotals: {
            /** Distinctitems */
            distinctItems: number;
            /** Totalevents */
            totalEvents: number;
        };
        /** UsageWriteResult */
        UsageWriteResult: {
            /**
             * Accepted
             * @default false
             * @constant
             */
            accepted: false;
            /**
             * Persistence
             * @default local-scanner
             * @constant
             */
            persistence: "local-scanner";
            /**
             * Reason
             * @default derived from configured session archives
             * @constant
             */
            reason: "derived from configured session archives";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    bootstrap_api_v1_bootstrap_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BootstrapResponse"];
                };
            };
        };
    };
    get_context_targets_api_v1_context_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextTargetsResponse"];
                };
            };
        };
    };
    get_context_target_api_v1_context__target__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                target: "claude" | "memory" | "codex";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextTargetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prepare_context_api_v1_context__target__prepare_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                target: "claude" | "memory" | "codex";
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ContextPrepareRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextPrepareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_context_api_v1_context__target__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                target: "claude" | "memory" | "codex";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContextConfirmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextConfirmResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_item_api_v1_items__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_catalog_item_content_api_v1_catalog_items__id__content_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CatalogContentUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogContentUpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_catalog_skill_api_v1_catalog_items_rename_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CatalogRenameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogRenameResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_catalog_skill_api_v1_catalog_items_delete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CatalogDeleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogDeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_app_health_api_v1_apps__app_id__health_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppHealthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    launch_app_api_v1_apps__app_id__launch_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppLaunchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rebuild_source_index_api_v1_sources_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ScanSourcesRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanSourcesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_usage_summary_api_v1_usage_summary_get: {
        parameters: {
            query?: {
                refresh?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_model_snapshot_api_v1_models_snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelSnapshotResponse"];
                };
            };
        };
    };
    refresh_models_api_v1_models_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelRefreshResponse"];
                };
            };
        };
    };
}
